SERVER_NAME = "#{ENV['USER']}S"
SERVER_IP = '192.168.56.110'

Vagrant.configure('2') do |cfg|
  cfg.vm.box = 'boxen/alpine-3.20'
  cfg.vm.synced_folder '.', '/vagrant'
  cfg.ssh.insert_key = false
  cfg.ssh.dsa_authentication = false

  cfg.vm.define SERVER_NAME do |control|
    control.vm.hostname = SERVER_NAME
    control.vm.network 'private_network', ip: SERVER_IP
    control.vm.provider 'virtualbox' do |v|
      v.name = SERVER_NAME
      v.cpus = 1
      v.memory = 1024
    end
    control.vm.provision 'shell', privileged: true, path: 'scripts/setup.sh'
  end
end
