USER = ENV['USER']
SERVER_NAME = "#{USER}S"
SERVER_IP = '192.168.56.110'
WORKER_NAME = "#{USER}SW"
WORKER_IP = '192.168.56.111'
TOKEN_PATH = '/vagrant/secrets/node-token'

Vagrant.configure('2') do |config|
  config.vm.box = 'boxen/alpine-3.20'
  config.vm.synced_folder '.', '/vagrant'
  config.ssh.insert_key = false
  config.ssh.dsa_authentication = false
  config.vm.boot_timeout = 600

  config.vm.provider 'virtualbox' do |v|
    v.cpus = 4
    v.memory = 4024
  end

  config.vm.define SERVER_NAME do |control|
    control.vm.hostname = SERVER_NAME
    control.vm.network 'private_network', ip: SERVER_IP
    control.vm.provider 'virtualbox' do |v|
      v.name = SERVER_NAME
    end
    control.vm.provision 'shell', privileged: true, path: 'scripts/setup_server.sh', args: [TOKEN_PATH]
  end

  config.vm.define WORKER_NAME do |worker|
    worker.vm.hostname = WORKER_NAME
    worker.vm.network 'private_network', ip: WORKER_IP
    worker.vm.provider 'virtualbox' do |v|
      v.name = WORKER_NAME
    end
    worker.vm.provision 'shell', privileged: true, path: 'scripts/setup_worker.sh', args: [TOKEN_PATH, SERVER_IP]
  end
end
